//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeurSmartCity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lieu
    {
        public int Id { get; private set; }
        public string nom { get; set; }
        public string type { get; set; }
        public string type_detail { get; set; }
        public string classement { get; set; }
        public string adresse { get; set; }
        public string codepostal { get; set; }
        public string commune { get; set; }
        public string telephone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string siteweb { get; set; }
        public string facebook { get; set; }
        public string ouverture { get; set; }
        public string tarifsenclair { get; set; }
        public string tarifsmin { get; set; }
        public string tarifsmax { get; set; }
        public string producteur { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<short> abscisses { get; set; }
        public Nullable<short> ordonnées { get; set; }
    }
}
