//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeurSmartCity.Models
{
    using System;
    using System.Collections.Generic;
    using ServeurSmartCity.JsonModel;
    
    public partial class Lieu
    {
        public int Id { get; private set; }
        public string nom { get; set; }
        public string type { get; set; }
        public string type_detail { get; set; }
        public string classement { get; set; }
        public string adresse { get; set; }
        public string codepostal { get; set; }
        public string commune { get; set; }
        public string telephone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string siteweb { get; set; }
        public string facebook { get; set; }
        public string ouverture { get; set; }
        public string tarifsenclair { get; set; }
        public string tarifsmin { get; set; }
        public string tarifsmax { get; set; }
        public string producteur { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<short> abscisses { get; set; }
        public Nullable<short> ordonnées { get; set; }

        public Lieu(Feature f)
        {
            Id = int.Parse(f.properties.id_sitra1);
            nom = f.properties.nom;
            type = f.properties.type;
            type_detail = f.properties.type_detail;
            classement = f.properties.classement;
            adresse = f.properties.adresse;
            codepostal = f.properties.codepostal;
            commune = f.properties.commune;
            telephone = f.properties.telephone;
            fax = f.properties.fax;
            email = f.properties.email;
            siteweb = f.properties.siteweb;
            facebook = f.properties.facebook;
            ouverture = f.properties.ouverture;
            tarifsenclair = f.properties.tarifsenclair;
            tarifsmin = f.properties.tarifsmin;
            tarifsmax = f.properties.tarifsmax;
            producteur = f.properties.producteur;
            latitude = f.geometry.coordinates[0];
            longitude = f.geometry.coordinates[1];
            //TODO : abscisses et ordonnées
        }
    }
}
