//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeurSmartCity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LieuResume
    {
        public int Id { get; set; }
        public string nom { get; set; }
        public string type { get; set; }
        public string ouverture { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<short> abscisses { get; set; }
        public Nullable<short> ordonnees { get; set; }
    }
}
